# Generated by Django 6.0.5 on 2026-05-16 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('category', models.CharField(choices=[('fermentation', 'Fermentação'), ('pcr', 'PCR'), ('extraction', 'Extração'), ('chromatography', 'Cromatografia'), ('microscopy', 'Microscopia'), ('cell_culture', 'Cultura de Células'), ('enzymatic', 'Enzimático'), ('other', 'Outro')], max_length=50, verbose_name='Categoria')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='protocols/', verbose_name='Arquivo PDF')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Protocolo',
                'verbose_name_plural': 'Protocolos',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='Versão')),
                ('change_description', models.TextField(verbose_name='Descrição da Alteração')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='protocols.protocol')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
